### ISSUE TITLE
Reference counting

### ISSUE THREAD

**Issue by inzanez** [cztomczak/cefcapi#14]
I might be wrong: But how can this example code work if reference counting is not really implemented?...

**Comment by cztomczak** [comment]
Reference counting is a technique to free memory automatically when it is not needed anymore, See https://en.wikipedia.org/wiki/Reference_counting . Otherwise you have to do it manually. In `examples/main_win.c` for example you can see the `app` variable that is created on stack. The `initialize_cef_app` function initializes the `cef_app_t` structure by assigning dummy reference counting methods among other things. The `app` variable is popped of the stack when `main` method completes, so that's how memory is freed in this case. In some cases you have to free CEF objects before shutdown is called (e.g. browser object), but that's not the case in our example.

**Comment by inzanez** [comment]
Oh, ok, I get it. That makes totally sense. Do you have any idea why running your example code with the current verison of CEF might fail? Building works fine, no issue, but running it gives some strange error messages like "exception: std::bad_array_new_length" at memory location xxx...can't figure out what's wrong here.

**Comment by cztomczak** [comment]
Only the CEF version specified in README is supported. I can suggest to go through all changes in API (and possibly commits and issues in the tracker) and see how it affects current code. Also make sure that current CEF supported version from README works fine on your machine and with your current tooling.
